### ISSUE TITLE
findAddressCandidates?

### ISSUE THREAD

**Issue by jakc** [Esri/esri-leaflet-geocoder#111]
I might be missing something, but does this component only support the find operation on the Esri World Geocoding service?  

I see in [the docco](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-find-address-candidates.htm), it mentions:

*The recommended operation to use is findAddressCandidates. Single field input is easier because the address parsing is done for you; however, multifield input may provide faster responses and more precise results.*

Our client has a requirement to separate out the address search into: street number, street name, postcode, state  (We are in Australia), thus I believe I would need to use findAddressCandidates.

**Comment by jgravois** [comment]
the [`L.esri.geosearch`](http://esri.github.io/esri-leaflet/examples/geocoding-control.html) UI control utilizes `find` because it collects single line input from the user. 

the underlying task, [`L.esri.Geocoding.geocode`](https://github.com/Esri/esri-leaflet-geocoder#lesrigeocodinggeocode) supports both. 

```js
L.esri.Geocoding.geocode().text("Denver").within(bounds).run(function(err, response){
  console.log(response);
});
>>> uses 'find'

L.esri.Geocoding.geocode().address('380 New York St').city('Redlands').region('California').postal(92373).run(function(err, results, response){
  console.log(results);
});
>>> uses 'findAddressCandidates'
```
`find` is used when `text` is supplied, `findAddressCandidates` is used when you discrete individual parameters are provided instead.

check out the [codeblock here](https://github.com/Esri/esri-leaflet-geocoder/blob/master/src/Tasks/Geocode.js#L52) to see under the hood.

**Comment by jgravois** [comment]
happy to chat more if you have any other questions.
