### ISSUE TITLE
Geocoder producing too many results

### ISSUE THREAD

**Issue by lucchez** [Esri/esri-leaflet-geocoder#129]
Browser and version: Version 51.0.2704.106 m (64-bit)
Version of Leaflet (L.version): 1.0.0-rc.2
Version of esri Leaflet (L.esri.VERSION): 2.0.1
Steps to reproduce the error:

After updating to esri-leaflet.js 2.0.1 and esri-leaflet-geocoder.js 2.1.0 multiple markers are placed for an address query. One of the markers in is the correct geographic location whereas, 2-4 extra markers are placed (along the same street) but incorrectly.

I have tried to limit the results with the following options: 
var searchControl = L.esri.Geocoding.geosearch({
providers: [arcgisOnline], useMapBounds: 15, maxResults: 1, allowMultipleResults: false
}).addTo(map);
But this has no effect.

I did not take the time to create a sjbin as the same issue occurs in the "Geocoding Control" example here: http://esri.github.io/esri-leaflet/examples/geocoding-control.html

The image provided is when I try to geocode (from search). 
![2016-07-21 08_54_10-geocoding control _ esri leaflet](https://cloud.githubusercontent.com/assets/6922974/17030810/2432cc2a-4f26-11e6-8e1e-c5582cd00f06.png)

**Comment by jgravois** [comment]
thanks for reporting this.  `maxResults` is actually an optional argument for individual ***providers***.

```js
var searchControl = L.esri.Geocoding.geosearch({
  providers: [
    L.esri.Geocoding.arcgisOnlineProvider({
      maxResults: 1
    })
  ]
}).addTo(map);
```
    
that said, even with the option set appropriately, you'll still see more than one candidate returned. i'll need to double check with the geocoding team to confirm, but i think its new behavior in the World Geocoding Service itself, and i'd argue that its inappropriate.

whats happening is that a request to the [`/find`](https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/find?outSr=4326&forStorage=false&outFields=*&maxLocations=20&text=291%20N%20Main%20St%2C%20Porterville%2C%20California%2C%20USA&magicKey=GST7YMc0AM9UOsE3GY8tIS9GOghnYnwZIip_GQypG1c915KOYshUUoaOYshUU1cpOh9bZgKZQoc3YSyaagDIZhkZQBwJCb1uDg9LDF4AZN4IDT5GOh5K1gAQOodF&f=pjson) of the World Geocoding Service that includes a `magicKey` (originally returned by `/suggest`) returns more than one result.

https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/find?outSr=4326&forStorage=false&outFields=*&maxLocations=20&text=291%20N%20Main%20St%2C%20Porterville%2C%20California%2C%20USA&magicKey=GST7YMc0AM9UOsE3GY8tIS9GOghnYnwZIip_GQypG1c915KOYshUUoaOYshUU1cpOh9bZgKZQoc3YSyaagDIZhkZQBwJCb1uDg9LDF4AZN4IDT5GOh5K1gAQOodF&f=pjson

it wouldn't be hard to trap for this in esri-leaflet-geocoder, but i'd like to gather a little more information before i make the change because i'm under the impression that the whole purpose of a `magicKey` is to let the World Geocoding Service know that an individual suggestion has already been selected and only one candidate should be returned.

```js
// https://github.com/Esri/esri-leaflet-geocoder/blob/master/src/Providers/ArcgisOnlineGeocoder.js#L50-L54

if (key) {
  request.key(key);
} /*else {
  request.maxLocations(this.options.maxResults);
}*/

// limit the number of candidates, whether a magicKey was included or not
if (this.options.maxResults) {
  request.maxLocations(this.options.maxResults);
}
```

**Comment by jgravois** [comment]
the geocoding team confirmed to me that in the future they'd like Address/StreetName geocoding requests that include a magicKey to *always* return a single candidate.  

in the meantime, i've merged a change here to ensure that we always pass through maxResults options to make sure you can control how many results are returned.

http://jsbin.com/kaxahupido/edit?html,output

let me know if you have any other questions.  i'd be happy to chat more.

**Comment by lucchez** [comment]
Thank you John,
I sincerely appreciate the prompt response and rapid resolution to the issue.
For my own edification please correct me if I am missing something, but it seems to me that a geocoding “result” should always return the “highest” scoring candidate; never more than one result.
In terms of other geo-referencing/ geo-locating methods you are typically trying to locate a specific/unique location.
I would think that this would be the desired result in terms of this geocoder functionality.
Thank you again for all your efforts.

[GIS_logo_for_email]

**Comment by jgravois** [comment]
@lucchez there are lots of different valid use cases. 

you can ask the World Geocoding Service to return a single candidate with the highest score. you can ask for more candidates to be returned and filter the results in your own code before showing a single match to a user.  in other situations you might prefer to show several results in your application and allow end users to evaluate their quality.

the goal for esri-leaflet-geocoder is:
1. to provide sensible defaults
2. give developers enough options to fulfill common requests
3. keep the library as simple and intuitive as possible
4. make sure everything is documented

if there's room for improvement *anywhere*, i'd always like to know.

**Comment by lucchez** [comment]
@jgravois 
Thank you for the clarification. I wasn't meaning to critique, but rather offering my own limited observation based on my specific use case. Thank you for the response and keep up the great work.
