### ISSUE TITLE
enhancement: set order of providers for suggested results

### ISSUE THREAD

**Issue by pmacMaps** [Esri/esri-leaflet-geocoder#217]
Not sure if this is even possible, but when using a mix of providers (say feature layer and geocode service), it would be nice to control which provider appears first in the suggestions.

I have an app where I would prefer suggestions from the feature layer appear first, but the suggestions from the geocode service typically appear first.

If this is possible, and you can steer me in the right direction, I can try to tackle it.

**Comment by jgravois** [comment]
that would make a really nice enhancement.

currently we're just processing each individual batch of suggestions sequentially, drawing them in the same order that responses from remote servers are received.

https://github.com/Esri/esri-leaflet-geocoder/blob/fd58a6b2c5b7156421d7cad9d7bfe3f27910d380/src/Controls/Geosearch.js#L71-L83

in order to achieve the behavior you describe, you'd need to:

1. find an opportunity to create a unique container for each provider
2. append each container to the DOM in the same order as the providers were supplied in the constructor.
3. use the appropriate container as the target when calling [`DomUtil.create()`](https://leafletjs.com/reference-1.4.0.html#domutil-create) for each individual header and suggestion (instead of `this._suggestions`, which is a container for _everything_ in the control).

https://github.com/Esri/esri-leaflet-geocoder/blob/fd58a6b2c5b7156421d7cad9d7bfe3f27910d380/src/Controls/Geosearch.js#L219

**Comment by pmacMaps** [comment]
@jwasilgeo, this is another opportunity to get involved with the Esri-Leaflet ecosystem.

**Comment by jwasilgeo** [comment]
I'm intrigued. Have you had a chance to try to give this a go? I'm happy to help collaborate and/or review along the way. Very open to discussing a bit more of course.

**Comment by pmacMaps** [comment]
I started digging in a little, but this is probably a bit beyond where I'm at as a developer currently.  I am open on working on it, but would need some coaching.

**Comment by jwasilgeo** [comment]
@pmacMaps thanks for your willingness to help out.

I finally found a free moment to start looking into this.  @jgravois I appreciate your advice on how we could do this with DOM manipulation alone.  Just to rule another idea out, could we instead go down the path of something along the lines of a `Promise.all` with the series of `XMLHttpRequest`s that get sent for each provider in this area?

https://github.com/Esri/esri-leaflet-geocoder/blob/fd58a6b2c5b7156421d7cad9d7bfe3f27910d380/src/Classes/GeosearchCore.js#L112-L118

My initial digging tells me this would require wiring up babel with rollup, and I'm not sure yet if altering the tooling and dev dependencies is worth it.

**Comment by jgravois** [comment]
that's definitely an option. (and not a bad one either).

support for Promises is pretty widespread now, but Esri Leaflet supports browsers [all the way back to IE8](https://github.com/Esri/esri-leaflet/wiki/FAQ#what-browsers-does-esri-leaflet-support), so you'd definitely have to transpile/polyfill.

one big drawback of that (besides the dev tooling) is that `L.esri.request`doesn't return a Promise. it was architected back in the days of callbacks.

if you're genuinely interested in modernizing the library, I'd probably suggest that you go whole hog and:
* resurrect [this PR](https://github.com/Esri/esri-leaflet/pull/1054) and let `@esri/arcgis-rest-request` 
* tag a `v3.x` that only supports modern/evergreen browsers

that'd be a lot more work than my initial suggestion here, but it has other merits.

**Comment by jwasilgeo** [comment]
Thank you for all this, @jgravois!  Still mulling it all over.  At the moment I am thinking I will probably go back to the DOM manipulation idea.

**Comment by jwasilgeo** [comment]
closed via PR #223

**Comment by pmacMaps** [comment]
Should there be a new minor or patch version release of this library with this enhancement?

**Comment by jwasilgeo** [comment]
Yes, good question, and I am hoping we can get that taken care of first thing next week.

**Comment by jwasilgeo** [comment]
@pmacMaps https://github.com/Esri/esri-leaflet-geocoder/releases/tag/v2.3.0
