### ISSUE TITLE
Suggestions appear underneath other map corner controls

### ISSUE THREAD

**Issue by jwasilgeo** [Esri/esri-leaflet-geocoder#230]
Suggestions appear underneath other map corner controls when the optional `position` property is either `'topleft'` or `'topright'`. Simply changing the `z-index` value does not appear to be a successful quick fix.

See more here:
https://github.com/Esri/esri-leaflet-geocoder/blob/298916c6e8983ebac1a1750f80e264d2266b1928/src/esri-leaflet-geocoder.css#L72-L85

![image](https://user-images.githubusercontent.com/4933392/67695639-64d8dd00-f973-11e9-9809-c83d7e21cdba.png)

**Comment by gavinr-maps** [comment]
Thanks for the additional info @sheeley820. I noticed the original item referenced:

> Simply changing the z-index value does not appear to be a successful quick fix.

So I'm wondering what that's referring to. But if you want to submit a PR for the z-index change and then we can do some testing, I'm ok with that.

**Comment by sheeley820** [comment]
@gavinr-maps Jacob thought, like I initially did, that the `z-index` needed to target the suggestions list (`.geocoder-control-suggestions`), but it needed to be on the control element as a whole.  Since `.leaflet-control` defines control `z-index` as `800` setting a higher `z-index` on child elements doesn't work.

Pull request [here](https://github.com/Esri/esri-leaflet-geocoder/pull/320)

**Comment by patrickarlt** [comment]
@sheeley820 I just released 3.15. It should be available on NPM and the CDD now! Thanks for the PR.
