### ISSUE TITLE
TypeScript types file

### ISSUE THREAD

**Issue by gavinr-maps** [Esri/esri-leaflet-geocoder#319]
# Problem

As a follow-up from #259 and https://github.com/Esri/esri-leaflet-geocoder/issues/318#issuecomment-2312706576, it seems like the TypeScript types at https://www.npmjs.com/package/@types/esri-leaflet are ok but not working in certain situations.

# Solution

We should publish our own typescript types file within this repo, like we did within https://github.com/Esri/esri-leaflet-vector/pull/114

# Replication Steps

1. Run the following in a terminal:

```bash
npm create vite@latest test-esri-leaflet-geocoder -- --template vanilla-ts
cd test-esri-leaflet-geocoder
npm install

npm install leaflet
npm i --save-dev @types/leaflet

npm install esri-leaflet-vector
npm install esri-leaflet-geocoder

npm run dev
```

2. add the following to the **top** of  `src/style.css`:

```css
@import url(https://unpkg.com/leaflet@1.9/dist/leaflet.css);
@import url(https://unpkg.com/esri-leaflet-geocoder/dist/esri-leaflet-geocoder.css);

#app {
  width: 800px;
  height: 400px;
}
```

REPLACE the file `src/main.ts` with this:

```jsx
import "./style.css";

import * as L from "leaflet";
// import * as esriLeaflet from "esri-leaflet";
import * as esriLeafletVector from "esri-leaflet-vector";
import * as esriLeafletGeocoder from "esri-leaflet-geocoder";

const createMap = (domNode: HTMLDivElement) => {
  const apikey =
    "YOUR_API_KEY";
  var map = L.map(domNode).setView([45.5165, -122.6764], 12);
  // esriLeaflet.basemapLayer("Streets").addTo(map);
  esriLeafletVector
    .vectorBasemapLayer("ArcGIS:Streets", {
      apikey,
    })
    .addTo(map);

  // create the geocoding control and add it to the map
  var searchControl = esriLeafletGeocoder
    .geosearch({
      providers: [
        esriLeafletGeocoder.arcgisOnlineProvider({
          // API Key to be passed to the ArcGIS Online Geocoding Service
          apikey,
        }),
      ],
    })
    .addTo(map);

  // create an empty layer group to store the results and add it to the map
  var results = L.layerGroup().addTo(map);

  // listen for the results event and add every result to the map
  searchControl.on("results", function (data: any) {
    results.clearLayers();
    for (var i = data.results.length - 1; i >= 0; i--) {
      results.addLayer(L.marker(data.results[i].latlng));
    }
  });
};
createMap(document.querySelector<HTMLDivElement>("#app")!);

```

3. Open the project in VS Code.

- Expected: No Typescript errors.
- Actual: Could not find a declaration file for module 'esri-leaflet-geocoder'. 'c:/../node_modules/esri-leaflet-geocoder/dist/esri-leaflet-geocoder-debug.js' implicitly has an 'any' type.   Try `npm i --save-dev @types/esri-leaflet-geocoder` if it exists or add a new declaration (.d.ts) file containing `declare module 'esri-leaflet-geocoder';`ts(7016)

**Comment by nooras** [comment]
Hey @gavinr 
I am interested in this task. Can you please assign me ?
Also which specific type need to be added ?

**Comment by hhkaos** [comment]
Sorry @nooras I just found out that @gavinr was out of the office last week. Let me ping @patrickarlt & @cyatteau

**Comment by kimmykokonut** [comment]
Is @nooras assigned to this? I don't want to pick up an issue if someone is already on it.

**Comment by nooras** [comment]
> Is @nooras assigned to this? I don't want to pick up an issue if someone is already on it.

Hey @kimmykokonut I am working on it. Thanks

**Comment by nooras** [comment]
hey @gavinr-maps, @hhkaos 
I am done with changes in local. how can i verify these changes are working fine in local ?

**Comment by nooras** [comment]
@gavinr-maps 
Please review the PR. Let me know if any changes required

**Comment by hhkaos** [comment]
I'm trying to test, but I'm not as familiar as I should be with TypeScript these days.... So I'm going to defer to @gavinr-maps  😅

**Comment by gavinr-maps** [comment]
@hhkaos I have added replication steps to the original issue above.

**Comment by hhkaos** [comment]
I have followed the steps.
Is the error in the IDE or the terminal?

At first, as I expected, the IDE still shows a couple of errors (because @nooras  changes shouldn't be present, right?):
<img width="1300" alt="Screenshot 2024-10-22 at 16 49 17" src="https://github.com/user-attachments/assets/085dde55-a979-4b80-9df3-78894262433c">


To test her changes, locally, I have:
1. Cloned  [her repo](https://github.com/nooras/esri-leaflet-geocoder/tree/feat-typescript-types) and switched to `feat-typescript-types` branch
2. Run `npm install` and `npm run build` successfully
3. Copied the files in the `dist` folder and replaced the files in `test-esri-leaflet-geocoder/node_modules/esri-leaflet-geocoder/dist` folder
4. Close the VSCode tab and open it again (but the errors are still there)

Is that the right way to test it? 😅 

The app is building and the terminal is not showing any errors:
![Screenshot 2024-10-22 at 17 17 23](https://github.com/user-attachments/assets/92a77195-50fb-4e94-807f-cc55c9a5e874)
<img width="536" alt="Screenshot 2024-10-22 at 17 18 43" src="https://github.com/user-attachments/assets/a164b814-b984-4940-a791-c6f435734e9c">

So... I'm confused because  you mention:
> Actual: Could not find a declaration file for module 'esri-leaflet-geocoder'. 'c:/../node_modules/esri-leaflet-geocoder/dist/esri-leaflet-geocoder-debug.js' implicitly has an 'any' type. Try npm i --save-dev @types/esri-leaflet-geocoder if it exists or add a new declaration (.d.ts) file containing declare module 'esri-leaflet-geocoder';ts(7016)

But I don't see that error anywhere. Does it mean it is fixed? 😅

**Comment by hhkaos** [comment]
@nooras, just FYI, I just checked with @gavinr-maps on a call, and the issue on my side was that I had @types/esri-leaflet-geocoder installed globally; that's why I didn't have that issue 😅. So you can proceed with [his instructions](https://github.com/Esri/esri-leaflet-geocoder/pull/321#pullrequestreview-2383006326)

Thanks!
