### ISSUE TITLE
How to use Geosearch in my input tag?

### ISSUE THREAD

**Issue by icaro56** [Esri/esri-leaflet-geocoder#32]
I have my html

<input type="search" id="s">

How to link Geosearch to input?

**Comment by jgravois** [comment]
i have a prototype (that still needs work) here
https://github.com/jgravois/esri-leaflet-geocoder/blob/input-form/debug/sample-no-map.html

/*
to do:
- [ ] try to revert to use `L.control` again and figure out how to override what Leaflet does to re-nest the divs in leaflet-control-container
- [ ] why isn't the font for suggestions in the css being picked up?
- [ ] how could you `center align` the input parent div?
- [ ] figure out why `<label>`s associated with the input tag are currently being squished
- [ ] make it so youre not *forced* to declare the input tag width manually
- [ ] why is the 'expanded' constructor option being ignored? (probably bound to leaflet-control-container css)

#### bigger picture
- [ ] if/how might this benefit from a more substantial reorganization

@ngoldman said he'd be gracious enough to take a quick look when he gets unburied from email mountain.

**Comment by jgravois** [comment]
just realized it'd be substantially easier to review my work in a PR...

**Comment by ngoldman** [comment]
@jgravois indeed! open one up and I'll take a look :grin:

**Comment by jgravois** [comment]
∆∆ (its #73)

**Comment by jgravois** [comment]
i'm not gonna lie @ngoldman.  i'm stumped.  check out my mock [Control](https://github.com/jgravois/esri-leaflet-geocoder/blob/class-control/src/Controls/DummyControl.js#L6-L8) and [Class](https://github.com/jgravois/esri-leaflet-geocoder/blob/class-control/src/Class/DummyClass.js) to see a simplified example of just how little i've accomplished.

the question is... how do i extend both `DummyClass` which contains the business logic **and** `L.Control` (so that i can get access to its built in hooks like [onAdd](http://leafletjs.com/reference.html#icontrol-onadd))

if i don't `extend()` both of them, what other wizardry is available?

**Comment by jgravois** [comment]
i'm having a *better late than never* month, so i finally wrote a demo plugin that shows how to wire up address search (with autocomplete) in Leaflet to your own html `<input >`

https://github.com/jgravois/bootstrap-geocoder

it bundles a couple utility functions from esri-leaflet and [`geosearchCore`](https://github.com/Esri/esri-leaflet-geocoder/blob/master/src/Classes/GeosearchCore.js) from esri-leaflet-geocoder using rollup and wires World Geocoding search to a generic bootstrap `<input>`.

i think it makes more sense to *not* try and integrate a generic control in this repo, so i'm going to go ahead and close this issue now.  that said, i'd be more than happy to chat if anyone has questions about working with my own demo or writing their own adaptation down the line.
