### ISSUE TITLE
On a custom provider shouldn't results have the geometry if exists?

### ISSUE THREAD

**Issue by rntdrts** [Esri/esri-leaflet-geocoder#81]
I mean if it's a custom service maybe we want to be able to do a lot more than only put a marker on the map... what do you think?

```javascript 
EsriLeafletGeocoding.Controls.Geosearch.Providers.FeatureLayer = L.esri.Services.FeatureLayerService.extend({

            (...)
            results: function(text, key, bounds, callback){
            (...)
                        results.push({ ... });
                        if (feature.geometry) {
                                    result.geometry = feature.geometry;
                        }

                                    or

                        results.push({
                                    geometry: feature.geometry,  //null or geometry
                                    latlng: bounds.getCenter(),
                                    bounds: bounds,
                                    text: this.options.formatSuggestion.call(this, feature),
                                    properties: feature.properties
                        });
            }
});```

**Comment by patrickarlt** [comment]
I was originally against this when I first wrote all of this because I wanted to keep all the results objects as similar as possible. Looking back this was probably totally unnecessary since all providers will be inherently different since `result.properties` is different depending on which provider it came from with no way to normalize.

As opposed to pushing just the geometry (which I would personally expect to be an instance of `L.Polygon`, ect...) I'm just going to add `result.geojson` which will be the full geojson feature. Which means you can do stuff like this.

```js
searchControl.on('results', function(e){
  for (var i = 0; i < e.results.length; i++) {
    var result = e.results[i];
    if (result.geojson) {
      L.geoJson(result.geojson).addTo(map);
    } else {
      L.marker(result.center).addTo(map);
    }
  }
});
```

Look for this in the next version!
