### ISSUE TITLE
arcgisOnlineProvider not honoring useMapBounds false?

### ISSUE THREAD

**Issue by andygup** [Esri/esri-leaflet-geocoder#94]
I haven't been able to get the geocoder to honor searching for world results. The results seem stuck within a fixed value of the visible map extent, maybe it's simply using the default value of `12`?

Example: http://jsbin.com/noluho > trying typing in `Boulder` or `Ft Collins`

```js

      var searchControl = L.esri.Geocoding.geosearch({ 
        useMapBounds: false,
        providers: [
          L.esri.Geocoding.arcgisOnlineProvider({
            countries: ['USA'],
            categories: ['Address', 'Postal', 'Populated Place','POI' ]
          })
        ]
      }).addTo(map);

```

**Comment by jgravois** [comment]
looks like a bug to me.  i think we just forgot to do something like [this](https://github.com/Esri/esri-leaflet/blob/master/src/Services/Service.js#L17), because when we step into [`Geosearch._searchBounds()`](https://github.com/Esri/esri-leaflet-geocoder/blob/master/src/Controls/Geosearch.js#L147-L161), `useMapBounds` is still set to the default value `12`.

for the time being you should be able to do something like this in your own code after instantiating the object:
```js
searchControl.options.useMapBounds = false
```
